// Writes every item's cssVars and the playground token stylesheet from registry/tradecn/tokens.json.
// `--check` fails when either is out of date, without writing.
import { writeFileSync, readFileSync, existsSync } from "node:fs"
import path from "node:path"
import {
  ROOT,
  REGISTRY_JSON,
  allTokenNames,
  cssVarsFor,
  readItemSources,
  readRegistry,
  readTokens,
  stableJson,
  tokensUsedIn,
} from "./lib/registry"

const check = process.argv.includes("--check")
const tokens = readTokens()
const names = allTokenNames(tokens)
const registry = readRegistry()
const problems: string[] = []

for (const item of registry.items) {
  // A theme's cssVars are written by hand and are the whole item. It has no files, so deriving them
  // from "the tokens its files use" comes to nothing, and writing that back would delete the theme.
  if (item.type === "registry:theme") continue
  const used = new Set<string>()
  for (const { source } of readItemSources(item)) for (const t of tokensUsedIn(source, names)) used.add(t)
  const want = cssVarsFor(used, tokens)
  const have = item.cssVars
  if (JSON.stringify(want ?? null) !== JSON.stringify(have ?? null)) {
    problems.push(`${item.name}: cssVars ${have ? "differ from" : "missing;"} tokens used: ${[...used].sort().join(", ") || "(none)"}`)
    if (want) item.cssVars = want
    else delete item.cssVars
  }
}

const css = renderStylesheet()
const cssPath = path.join(ROOT, "playground/src/styles/tradecn-tokens.css")
const cssCurrent = existsSync(cssPath) ? readFileSync(cssPath, "utf8") : ""
if (cssCurrent !== css) problems.push("playground/src/styles/tradecn-tokens.css is out of date")

if (check) {
  if (problems.length) {
    console.error("sync-tokens --check failed:\n  " + problems.join("\n  ") + "\nRun `just tokens`.")
    process.exit(1)
  }
  console.log("tokens in sync")
} else {
  writeFileSync(REGISTRY_JSON, stableJson(registry))
  writeFileSync(cssPath, css)
  console.log(problems.length ? "updated:\n  " + problems.join("\n  ") : "tokens already in sync")
}

function renderStylesheet(): string {
  const block = (selector: string, vars: Record<string, string>) =>
    Object.keys(vars).length
      ? `${selector} {\n${Object.keys(vars)
          .sort()
          .map((k) => `  --${k}: ${vars[k]};`)
          .join("\n")}\n}\n`
      : ""
  const colorKeys = [...new Set([...Object.keys(tokens.light), ...Object.keys(tokens.dark)])].sort()
  const theme = [
    ...Object.keys(tokens.theme)
      .sort()
      .map((k) => `  --${k}: ${tokens.theme[k]};`),
    ...colorKeys.map((k) => `  --color-${k}: var(--${k});`),
  ]
  return (
    "/* Generated by scripts/sync-tokens.ts from registry/tradecn/tokens.json. Do not edit.\n" +
    "   This is what the shadcn CLI writes into a consumer's stylesheet when it installs a tradecn item. */\n\n" +
    block(":root", tokens.light) +
    "\n" +
    block(".dark", tokens.dark) +
    "\n@theme inline {\n" +
    theme.join("\n") +
    "\n}\n"
  )
}
